export const urlConstants = {
  SERVICES: {
    UNNATI: "improvement-project/api/",
    KENDRA: "kendra/api/",
    SAMIKSHA: "",
    DHITI: "",
    SUNBIRD: "sunbird/api/",
  },
  API_URLS: {

    PROGRAM_LISTING: "v1/users/programs?",
    GET_PROJECTS: "v1/userProjects/getProject?page=",
    SOLUTIONS_LISTING: "v1/users/solutions/",
    GET_PROJECT: "v2/userProjects/details",


    NOTIFICATIONs_LIST: "v1/notifications/in-app/list",
    NOTIFICATION_COUNT: "v1/notifications/in-app/unReadCount",
    PROJECTS_LIST: "v1/userProjects/list",
    LIBRARY_CATEGORIES: "v1/library/categories/list",
    TEMPLATES_LIST: "v1/library/categories/projects/",
    TEMPLATE_DATA: "v1/library/categories/projectDetails/",
    CREATE_PROJECT_FORM: "v1/userProjects/metaForm",
    TEMPLATE_SORT: "v1/library/categories/projects",
    REGISTERDEVICE: "v1/notifications/push/registerDevice",
    PRIVATE_PROGRAMS: "v1/users/privatePrograms",
    GET_PROFILE: "v2/user-extension/getProfile",
    GET_STATES: "v2/entities/listByEntityType/state",
    GET_SUBENTITIES: "v1/entities/subEntityTypeList/",
    GET_ENTITY_LIST: "v1/entities/subEntityList/",
    IMPORT_TEMPLATE: "v1/userProjects/importFromLibrary/",
    GET_REPORT: "v1/reports/entity/",
    GET_REPORT_TYPES: "v1/reports/types",
    GET_ENTITY_TYPES: "v1/user-extension/getEntityTypes",
    GET_ENTITIES_BY_TYPE: "v1/user-extension/getEntities",
    GET_FULL_REPORT: "v1/reports/detailView/",
    GET_PROGRAM_BY_ENTITY: "v1/reports/getProgramsByEntity/",
    GET_TASK_META_FORM: "v1/userProjects/tasksMetaForm",
    GET_LEARNING_RESOURCES: "v1/learningResources/list",
    LEARNING_RESOURCES_LIST: "v1/learning-resources/list?",
    GET_DYNAMIC_LINKS: "v1/static-links/list",
    GET_LEARNING_RESOURCES_FILTERS: "v1/learning-resources/filters",
    PROFILE_INFO: "v1/users/getProfile",
    SYNC_PROJECT: 'v1/userProjects/sync/',
    CREATE_PROJECT_DOC: "v1/userProjects/create",
    GET_IMAGE_UPLOAD_URLS: "v1/userProjects/getFileUploadUrl",
    START_ASSESSMENT: 'v1/userProjects/solutionDetails/',
    PROJCET_TASK_STATUS: "v1/userProjects/tasksStatus/",
    LIBRARY_SEARCH: "v1/library/categories/projects?search=",
    STATE_LIST: "v1/entities/listByEntityType/state",
    STATE_ROLES: "v1/entities/subEntitiesRoles/",
    ENTITY_MAPPING_FORM: "v1/users/entitiesMappingForm/",
    PROFILE_UPDATE: "v1/user-extension/updateProfileRoles",
    MARK_AS_READ: "v1/notifications/in-app/markAsRead/",
    GET_PREVIOUS_PROFILE: "v1/users/search?search="
  },
};
