version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.20.1
    steps:
      - checkout
      - run:
          name: Check current version of node
          command: node -v
      - restore_cache:
          keys:
            - node_modules_cache_{{ checksum "package-lock.json" }}
      - run:
          name: Install project dependencies
          command: |
            if [ ! -d "node_modules" ]; then
            npm i -f
            fi
          no_output_timeout: 60m
      - save_cache:
          key: node_modules_cache_{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Run Tests
          command: npm run test:ci
      - store_artifacts:
          path: coverage
