const path = require('path');
var fs = require('fs');

function deleteUnUsableIosIcon(ionicIconFilePath) {
    try {
        const files = fs.readdirSync(ionicIconFilePath);
        files.forEach(function (file) {
            if (!([
                "add.svg",
                "close.svg",
                "caret-forward-circle", // ionic 4 -> 5, md replacement of "arrow-dropright-circle.svg",
                "chevron-forward-circle", // ionic 4 -> 5, ios replacement of "arrow-dropright-circle.svg",
                "caret-down-circle", // ionic 4 -> 5, md replacement of "arrow-dropdown.svg",
                "chevron-down-circle", // ionic 4 -> 5, ios replacement of "arrow-dropdown.svg",
                "caret-up", // ionic 4 -> 5, md replacement of "arrow-dropup.svg",
                "chevron-up-circle-outline", // ionic 4 -> 5, ios replacement of "arrow-dropup.svg",
                "arrow-up.svg",
                "arrow-down.svg",
                "alert.svg",
                "star.svg",
                "cloud-download.svg",
                "trash.svg",
                "share.svg",
                "information-circle-outline.svg",
                "star-outline.svg",
                "refresh.svg",
                "print.svg",
                "sad.svg",
                "warning.svg",
                "arrow-back.svg",
                "arrow-forward.svg",
                "albums.svg",
                "information-circle.svg",
                "settings.svg",
                "person.svg",
                "stats-chart", // ionic 4 -> 5, renamed from stats.svg",
                "checkmark.svg",
                "remove.svg",
                "play.svg",
                "notifications.svg",
                "notifications-circle-outline", // ionic 4 -> 5, replacement of "notifications-outline.svg",
                "arrow-forward", // ionic 4 -> 5, replacement of "arrow-round-forward.svg",
                "refresh-circle.svg",
                "start.svg",
                "ellipsis-horizontal.svg", // ionic 4 -> 5, ios replacement of "more.svg",
                "ellipsis-vertical.svg", // ionic 4 -> 5, md replacement of "more.svg",
                "time.svg",
                "checkmark-circle.svg",
                "create.svg",
                "call.svg",
                "mail.svg",
                "arrow-down.svg", // ionic 4 -> 5, replacement of "arrow-round-down.svg",
                "download.svg",
                "search.svg",
                "close-circle.svg",
                "eye.svg",
                "alert-circle-outline.svg",
                'ios-caret-down.svg',
                'ios-caret-forward.svg',
                'ios-cloud-done.svg',
                'ios-cloud-offline-outline.svg',
                'ios-document.svg',
                'ios-radio-button-off-outline.svg',
                'ios-attach.svg',
                'ios-camera.svg',
                'ios-create.svg',
                'ios-person-outline.svg',
                'ios-share-social.svg',
                'ios-calendar-outline.svg',
                'ios-newspaper-outline.svg',
                'ios-attach-outline.svg',
                'ios-image-outline.svg',
                'ios-attach-outline.svg',
                'ios-book.svg',
                'ios-checkmark-circle.svg',
                'ios-contrast.svg',
                'ios-cloud-done.svg',
                'ios-list-box.svg',
                'ios-clipboard.svg',
                'ios-document.svg',
                'ios-volume-medium.svg',
                'ios-videocam.svg',
                'ios-options.svg',
                'ios-more.svg',
                'ios-download.svg',
                'ios-share.svg',
                'ios-ellipsis-vertical.svg',
                'ios-caret-down.svg',
                'ios-arrow-dropup-circle.svg',
                'ios-information-circle.svg',
                'ios-bulb.svg',
                'md-camera.svg',
                'md-document.svg',
                'md-cloud-upload.svg',
                'md-filing.svg',
                'md-caret-down.svg',
                'md-caret-forward.svg',
                'md-cloud-done.svg',
                'md-cloud-offline.svg',
                'md-document.svg',
                'md-radio-button-off-outline.svg',
                'md-attach.svg',
                'md-person.svg',
                'md-share-social.svg',
                'md-calendar.svg',
                'md-newspaper.svg',
                'md-attach.svg',
                'md-image.svg',
                'md-map.svg',
                'md-book.svg',
                'md-checkmark-circle.svg',
                'md-contrast.svg',
                'md-cloud-done.svg',
                'md-list-box.svg',
                'md-caret-down-outline.svg',
                'md-location-outline.svg',
                'md-link-outline.svg',
                'md-caret-down.svg',
                'md-radio-button-off.svg',
                'md-location.svg',
                'md-link.svg',
                'md-funnel.svg',
                'md-clipboard.svg',
                'md-caret-down.svg',
                'md-radio-button-off.svg',
                'md-document.svg',
                'md-volume-medium.svg',
                'md-videocam.svg',
                'md-options.svg',
                'md-downlaod.svg',
                'md-more.svg',
                'md-share.svg',
                'md-caret-down.svg',
                'md-person.svg',
                'md-share-social.svg',
                'md-calendar.svg',
                'md-newspaper.svg',
                'md-image.svg',
                'md-attach.svg',
                'md-add.svg',
                'md-chevron-forward.svg',
                'md-cloud-offline.svg',
                'md-cloud-outline.svg',
                'md-cloud-upload.svg',
                'md-ellipsis-vertical.svg',
                'md-caret-down.svg',
                'md-arrow-dropup-circle.svg',
                'md-add-circle.svg',
                'md-arrow-dropdown.svg',
                'md-arrow-dropright.svg',
                'md-musical-notes.svg',
                'md-videocam.svg',
                'md-information-circle.svg',
                'md-bulb.svg'
            ].includes(file))) {
                fs.unlinkSync(ionicIconFilePath + '/' + file);
            }
        });
    } catch (e) {
        console.error(e);
    }
}

module.exports = function (context) {
    var ionicIconFolderPath;

    ionicIconFolderPath = path.join(__dirname, '../www/svg');
    console.log('deleted unusable Icon from www/svg');
    deleteUnUsableIosIcon(ionicIconFolderPath);
}

var ionicIconFolderPath;

ionicIconFolderPath = path.join(__dirname, '../www/svg');
console.log('deleted unusable Icon from www/svg');
deleteUnUsableIosIcon(ionicIconFolderPath);